Import Dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#Data colllection And Preprocessing

In [36]:
#load data from csv file to pandas datafrme
movies_data = pd.read_csv('/content/tmdb_5000_movies.csv')

In [5]:
movies_data.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [6]:
movies_data.shape

(4803, 20)

In [12]:
# selecting the relevant features for recommendation
selected_features = ['genres','keywords','tagline','title']
print(selected_features)

['genres', 'keywords', 'tagline', 'title']


In [13]:
# replacing the null valuess with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [14]:
# combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['title']

In [15]:
print(combined_features)

0       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1       [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3       [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4       [{"id": 28, "name": "Action"}, {"id": 12, "nam...
                              ...                        
4798    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4799    [{"id": 35, "name": "Comedy"}, {"id": 10749, "...
4800    [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...
4801      [] [] A New Yorker in Shanghai Shanghai Calling
4802    [{"id": 99, "name": "Documentary"}] [{"id": 15...
Length: 4803, dtype: object


In [16]:
# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

In [17]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [18]:
print(feature_vectors)

  (0, 10557)	0.13462068455768822
  (0, 17053)	0.1264131365559928
  (0, 16827)	0.03677451715556411
  (0, 21054)	0.05974278518830791
  (0, 19898)	0.027110793753929576
  (0, 13187)	0.11234678719622088
  (0, 7827)	0.07780511736416891
  (0, 5749)	0.07844152612499841
  (0, 19139)	0.09514776886043218
  (0, 10259)	0.047887213423191445
  (0, 16236)	0.09075670454964721
  (0, 5468)	0.12348373587695455
  (0, 18018)	0.11886148454690604
  (0, 17538)	0.08089127265858193
  (0, 5019)	0.12999843322763968
  (0, 10306)	0.09260554885931364
  (0, 2743)	0.13462068455768822
  (0, 10073)	0.09300229051379177
  (0, 15792)	0.05229282478850778
  (0, 1070)	0.12999843322763968
  (0, 10740)	0.07927421092466416
  (0, 1034)	0.0965875871854387
  (0, 19095)	0.08471460658222557
  (0, 839)	0.09300229051379177
  (0, 15974)	0.09041115960539783
  :	:
  (4800, 18278)	0.07589410064812095
  (4800, 16552)	0.28740403664806075
  (4800, 14781)	0.28740403664806075
  (4801, 21139)	0.4521187840768643
  (4801, 11353)	0.3955727880780622


Cosine Similarity

In [19]:
similarity = cosine_similarity(feature_vectors)

In [20]:
print(similarity)

[[1.         0.32012104 0.25219792 ... 0.24024477 0.         0.16269787]
 [0.32012104 1.         0.23379801 ... 0.2309905  0.         0.14149163]
 [0.25219792 0.23379801 1.         ... 0.17032297 0.         0.11937159]
 ...
 [0.24024477 0.2309905  0.17032297 ... 1.         0.         0.15806694]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.16269787 0.14149163 0.11937159 ... 0.15806694 0.         1.        ]]


In [21]:
print(similarity.shape)

(4803, 4803)


Get movie name from User

In [30]:
# getting the movie name from the user

movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : Rush Hour


In [31]:
# creating a list with all the movie names given in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [32]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Rush Hour 3', 'Rush Hour 2', 'Rushmore']


In [33]:
close_match = find_close_match[0]
print(close_match)

Rush Hour 3


In [39]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['vote_count'].values[0]
print(index_of_the_movie)

783


In [40]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.20842987508803856), (1, 0.18813981080810355), (2, 0.2131082962768021), (3, 0.19877176159701954), (4, 0.21394057227992896), (5, 0.1960219418958683), (6, 0.17922148618918898), (7, 0.1951109307117425), (8, 0.15633686848959058), (9, 0.1618129374839365), (10, 0.19587604851294968), (11, 0.14051541201842183), (12, 0.1829170238371141), (13, 0.14907762904636784), (14, 0.1825900587051847), (15, 0.2174139908433279), (16, 0.18493510182135497), (17, 0.1990268210351469), (18, 0.13669050234335056), (19, 0.14630666113684804), (20, 0.1640397764846115), (21, 0.11990501269125992), (22, 0.11534376452457418), (23, 0.1573837533785046), (24, 0.1653619807829683), (25, 0.182921998416041), (26, 0.19284216104718427), (27, 0.19557195890176354), (28, 0.1856691588456299), (29, 0.19761075535447792), (30, 0.1860513471327229), (31, 0.18677537142085904), (32, 0.17935128374346976), (33, 0.18789063304413178), (34, 0.132204753007601), (35, 0.16843355440073005), (36, 0.13270944731274395), (37, 0.15745765564055778), 

In [41]:
len(similarity_score)

4803

In [42]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(783, 1.0000000000000002), (2942, 0.4123800834455775), (1025, 0.40572110656097554), (1537, 0.3050788832193864), (3778, 0.2869301441892069), (1945, 0.28306860477174267), (664, 0.2807805236500268), (451, 0.2803644160765424), (1532, 0.27878911978342796), (2156, 0.2777111476648002), (1373, 0.27004722824333), (3516, 0.26983470867124404), (1882, 0.2690434089007204), (2881, 0.26835876880900056), (183, 0.26805218878262177), (4615, 0.26687327184502296), (2859, 0.266052814095012), (2428, 0.2646091212323688), (2442, 0.2609922974136817), (470, 0.257652856218449), (2799, 0.2572169129731231), (2217, 0.25544146850182414), (2923, 0.25373703736427883), (2683, 0.25343288364490957), (3373, 0.25258988756403705), (176, 0.2519876569705916), (665, 0.24919356093963746), (2014, 0.24867661252762946), (1328, 0.2457161354425976), (180, 0.24484631261537765), (123, 0.24455955475012875), (1666, 0.2445504280299905), (1133, 0.24286950735056903), (2827, 0.24209845133249783), (1401, 0.2419052138473406), (3639, 0.240765

In [43]:
# print the name of similar movies based on the index

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Mortdecai
2 . Woman in Gold
3 . The Thomas Crown Affair
4 . Get Shorty
5 . The Art of Getting By
6 . The Best Offer
7 . Hudson Hawk
8 . The Haunting
9 . The Grand Budapest Hotel
10 . Nancy Drew
11 . The English Patient
12 . The Train
13 . Crocodile Dundee in Los Angeles
14 . The Great Beauty
15 . The Hunger Games: Catching Fire
16 . Pierrot le Fou
17 . Girl with a Pearl Earring
18 . Brooklyn's Finest
19 . Southland Tales
20 . What Dreams May Come
21 . Dancer in the Dark
22 . Everyone Says I Love You
23 . St. Trinian's
24 . All About the Benjamins
25 . The Other Side of Heaven
26 . The Revenant
27 . Lucky Numbers
28 . 1408
29 . The Town


Movie Recommendation System

In [45]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['vote_count'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : bat man
Movies suggested for you : 

1 . The Conjuring
2 . The Conjuring 2
3 . The Woman in Black
4 . Paranormal Activity 3
5 . The Apparition
6 . The Wailing
7 . In the Heart of the Sea
8 . Your Sister's Sister
9 . Howards End
10 . Brooklyn's Finest
11 . The Immigrant
12 . Southland Tales
13 . Grave Encounters
14 . Everyone Says I Love You
15 . 27 Dresses
16 . The Awakening
17 . The Visit
18 . Captive
19 . Frequency
20 . When the Lights Went Out
21 . Race to Witch Mountain
22 . Straight Outta Compton
23 . The Amityville Horror
24 . Interstellar
25 . GoodFellas
26 . Lights Out
27 . 127 Hours
28 . Rabbit-Proof Fence
29 . Dreamer: Inspired By a True Story


# End of Project Thank you!!!